// App
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const ERROR_HAPPENED = 'ERROR_HAPPENED';
export const BTC_MONEY_CHANGE = 'BTC_MONEY_CHANGE';
export const FAKE_MONEY_CHANGE = 'FAKE_MONEY_CHANGE';